# Suhyun Hwang

# Homework 6

# Friday Sep 24, 2021

In [1]:
import numpy as np

#### Problem 1

In [2]:
print( 'Problem 1' )

Problem 1


#### Problem 2

In [3]:
print( 'Problem 2' )

Problem 2


In [4]:
import matplotlib.pyplot as plt

In [5]:
x = np.arange(1, 100.1, 0.5)

In [6]:
print( x )

[  1.    1.5   2.    2.5   3.    3.5   4.    4.5   5.    5.5   6.    6.5
   7.    7.5   8.    8.5   9.    9.5  10.   10.5  11.   11.5  12.   12.5
  13.   13.5  14.   14.5  15.   15.5  16.   16.5  17.   17.5  18.   18.5
  19.   19.5  20.   20.5  21.   21.5  22.   22.5  23.   23.5  24.   24.5
  25.   25.5  26.   26.5  27.   27.5  28.   28.5  29.   29.5  30.   30.5
  31.   31.5  32.   32.5  33.   33.5  34.   34.5  35.   35.5  36.   36.5
  37.   37.5  38.   38.5  39.   39.5  40.   40.5  41.   41.5  42.   42.5
  43.   43.5  44.   44.5  45.   45.5  46.   46.5  47.   47.5  48.   48.5
  49.   49.5  50.   50.5  51.   51.5  52.   52.5  53.   53.5  54.   54.5
  55.   55.5  56.   56.5  57.   57.5  58.   58.5  59.   59.5  60.   60.5
  61.   61.5  62.   62.5  63.   63.5  64.   64.5  65.   65.5  66.   66.5
  67.   67.5  68.   68.5  69.   69.5  70.   70.5  71.   71.5  72.   72.5
  73.   73.5  74.   74.5  75.   75.5  76.   76.5  77.   77.5  78.   78.5
  79.   79.5  80.   80.5  81.   81.5  82.   82.5  8

In [7]:
y = np.log10( x )

In [8]:
z = np.sqrt( x )

In [9]:
plt.plot( y, z )

In [10]:
plt.plot( y, color = 'pink', linestyle = '--', linewidth = 2 )
plt.plot( z, color = 'purple', linestyle = '-', linewidth = 4 )

In [11]:
plt.titles( 'Function for HW6', fontsize = 44 )

AttributeError: module 'matplotlib.pyplot' has no attribute 'titles'

In [12]:
plt.savefig( 'Function for HW6', format = 'pdf' )

#plt.savefig( 'my_first_saved_figure.pdf', format = 'pdf', 
#            dpi = 1200, bbox_inches = 'tight', pad_inches = 0.3 )

In [13]:
plt.figure( figsize = ( 15,15 ) )
plt.ythicks( fontsize = 20 )
plt.xthicks( fontsize = 30 )

AttributeError: module 'matplotlib.pyplot' has no attribute 'ythicks'

#### Problem 3

In [14]:
print( 'Problem 3' )

Problem 3


In [15]:
q = np.array([ 45, 24, 5, 30, 3, 67, 33, 60, 65, 13, 82, 75, 21, 77, 67, 8, 86, 62, 23, 70, 11, 70, 21, 15, 84, 51, 6, 79, 78, 66, 2, 93, 49, 74, 23, 85, 25, 38, 1, 89 ])

In [16]:
print( q )

[45 24  5 30  3 67 33 60 65 13 82 75 21 77 67  8 86 62 23 70 11 70 21 15
 84 51  6 79 78 66  2 93 49 74 23 85 25 38  1 89]


In [17]:
np.where( q > 50 )

(array([ 5,  7,  8, 10, 11, 13, 14, 16, 17, 19, 21, 24, 25, 27, 28, 29, 31,
        33, 35, 39], dtype=int64),)

In [18]:
print( q[(q > 50 ) & (q < 70)] )

[67 60 65 67 62 51 66]


In [19]:
test_list = z

In [20]:
print( test_list )

[ 1.          1.22474487  1.41421356  1.58113883  1.73205081  1.87082869
  2.          2.12132034  2.23606798  2.34520788  2.44948974  2.54950976
  2.64575131  2.73861279  2.82842712  2.91547595  3.          3.082207
  3.16227766  3.24037035  3.31662479  3.39116499  3.46410162  3.53553391
  3.60555128  3.67423461  3.74165739  3.80788655  3.87298335  3.93700394
  4.          4.0620192   4.12310563  4.18330013  4.24264069  4.30116263
  4.35889894  4.41588043  4.47213595  4.52769257  4.58257569  4.63680925
  4.69041576  4.74341649  4.79583152  4.84767986  4.89897949  4.94974747
  5.          5.04975247  5.09901951  5.14781507  5.19615242  5.24404424
  5.29150262  5.33853913  5.38516481  5.43139025  5.47722558  5.52268051
  5.56776436  5.61248608  5.65685425  5.70087713  5.74456265  5.78791845
  5.83095189  5.87367006  5.91607978  5.95818764  6.          6.04152299
  6.08276253  6.12372436  6.164414    6.20483682  6.244998    6.28490254
  6.32455532  6.36396103  6.40312424  6.44204936  6.4

In [21]:
print( z[ 11 : 14 ] )

[2.54950976 2.64575131 2.73861279]


In [22]:
test_list [28] = 42.0

In [23]:
print( test_list )

[ 1.          1.22474487  1.41421356  1.58113883  1.73205081  1.87082869
  2.          2.12132034  2.23606798  2.34520788  2.44948974  2.54950976
  2.64575131  2.73861279  2.82842712  2.91547595  3.          3.082207
  3.16227766  3.24037035  3.31662479  3.39116499  3.46410162  3.53553391
  3.60555128  3.67423461  3.74165739  3.80788655 42.          3.93700394
  4.          4.0620192   4.12310563  4.18330013  4.24264069  4.30116263
  4.35889894  4.41588043  4.47213595  4.52769257  4.58257569  4.63680925
  4.69041576  4.74341649  4.79583152  4.84767986  4.89897949  4.94974747
  5.          5.04975247  5.09901951  5.14781507  5.19615242  5.24404424
  5.29150262  5.33853913  5.38516481  5.43139025  5.47722558  5.52268051
  5.56776436  5.61248608  5.65685425  5.70087713  5.74456265  5.78791845
  5.83095189  5.87367006  5.91607978  5.95818764  6.          6.04152299
  6.08276253  6.12372436  6.164414    6.20483682  6.244998    6.28490254
  6.32455532  6.36396103  6.40312424  6.44204936  6.4

#### Changing element 28 of test_list to 42.0

After running 'test_list [28] = 42.0' the element successfully changed 
We can see above that the 28th of the element is shown as 42. 

In [31]:
test_tuple = z

In [32]:
print( test_tuple [20] )

3.3166247903554


In [33]:
test_tuple[21] = 44.0

In [34]:
print( test_tuple )

[ 1.          1.22474487  1.41421356  1.58113883  1.73205081  1.87082869
  2.          2.12132034  2.23606798  2.34520788  2.44948974  2.54950976
  2.64575131  2.73861279  2.82842712  2.91547595  3.          3.082207
  3.16227766  3.24037035  3.31662479 44.          3.46410162  3.53553391
  3.60555128  3.67423461  3.74165739  3.80788655 42.          3.93700394
  4.          4.0620192   4.12310563  4.18330013  4.24264069  4.30116263
  4.35889894  4.41588043  4.47213595  4.52769257  4.58257569  4.63680925
  4.69041576  4.74341649  4.79583152  4.84767986  4.89897949  4.94974747
  5.          5.04975247  5.09901951  5.14781507  5.19615242  5.24404424
  5.29150262  5.33853913  5.38516481  5.43139025  5.47722558  5.52268051
  5.56776436  5.61248608  5.65685425  5.70087713  5.74456265  5.78791845
  5.83095189  5.87367006  5.91607978  5.95818764  6.          6.04152299
  6.08276253  6.12372436  6.164414    6.20483682  6.244998    6.28490254
  6.32455532  6.36396103  6.40312424  6.44204936  6.4

#### Changing element 21 of test_tuple to 44.0

After running 'test_tuple [21] = 44.0' the element successfully changed We can see above that the 21st of the element is shown as 44.

#### Problem 4

In [35]:
print( 'Problem 4' )

Problem 4
